version: '3.8'

services:
  localify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - STORAGE_PATH=/app/data/storage
      - MEDIA_PATH=/app/data/media
      - DB_NAME=localify.db
      - JWT_SECRET=${JWT_SECRET:-your_default_jwt_secret}
    volumes:
      - ./data/storage:/app/data/storage
      - ./data/media:/app/data/media
    restart: unless-stopped 