version: '3.8'

services:
  localify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4500:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your_default_jwt_secret}
    volumes:
      - ./storage:/storage
      - ./media:/media
    restart: unless-stopped 